


let data= [
    
  
    
  {
    id : 0,
    type : "flyers Design",
    title : "신풍닭발",
    exper1 : "Photoshop",
    exper2 : "illustration",
    exper3 : "HTML",
    exper4 : "CSS",
    term : "2014.09",
    url : "https://github.com/hyey00n/content/blob/main/repository/90004-1.png?raw=true",
    content : "‘시각장애인 전용도로는  주는 것은 바닥에 이라는 의미를 담고 있습니다주는 것은 바닥에 이라.",
  },
  

  {
    id : 1,
    type : "flyers Design",
    title : "원호 숯불갈비",
    exper1 : "Photoshop",
    exper2 : "illustration",
    exper3 : "HTML",
    exper4 : "CSS",
    term : "2014.09",
    url : "https://github.com/hyey00n/content/blob/main/repository/90004-3.png?raw=true",
    content : "‘시각장애인 전용도로는  주는 것은 바닥에 배치되어 있는 노란색 점자블록이라는 의미를 담고 있습니다.",
  },

  {
    id : 2,
    type : "flyers Design",
    title : "원호 숯불갈비",
    exper1 : "Photoshop",
    exper2 : "illustration",
    exper3 : "HTML",
    exper4 : "CSS",
    term : "2014.09",
    url : "https://github.com/hyey00n/content/blob/main/repository/90004-4.png?raw=true",
    content : "‘시각장애인 전용도로는  주는 것은 바닥에 배치되어 있는 노란색 점자블록이라는 의미를 담고 있습니다.",
  },
  {
    id : 2,
    type : "flyers Design",
    title : "뉴바디 뉴이어",
    exper1 : "Photoshop",
    exper2 : "illustration",
    exper3 : "HTML",
    exper4 : "CSS",
    term : "2014.09",
    url : "https://github.com/hyey00n/content/blob/main/repository/90004-5.png?raw=true",
    content : "‘시각장애인 전용도로는  주는 것은 바닥에 배치되어 있는 노란색 점자블록이라는 의미를 담고 있습니다.",
  },
  {
    id : 2,
    type : "flyers Design",
    title : "무드인테리어",
    exper1 : "Photoshop",
    exper2 : "illustration",
    exper3 : "HTML",
    exper4 : "CSS",
    term : "2014.09",
    url : "https://github.com/hyey00n/content/blob/main/repository/90004-6.png?raw=true",
    content : "‘시각장애인 전용도로는  주는 것은 바닥에 배치되어 있는 노란색 점자블록이라는 의미를 담고 있습니다.",
  },
  {
    id : 2,
    type : "flyers Design",
    title : "인생퍼스널트레이닝",
    exper1 : "Photoshop",
    exper2 : "illustration",
    exper3 : "HTML",
    exper4 : "CSS",
    term : "2014.09",
    url : "https://github.com/hyey00n/content/blob/main/repository/90004-7.png?raw=true",
    content : "‘시각장애인 전용도로는  주는 것은 바닥에 배치되어 있는 노란색 점자블록이라는 의미를 담고 있습니다.",
  },
  {
    id : 2,
    type : "flyers Design",
    title : "필라테스마르즈",
    exper1 : "Photoshop",
    exper2 : "illustration",
    exper3 : "HTML",
    exper4 : "CSS",
    term : "2014.09",
    url : "https://github.com/hyey00n/content/blob/main/repository/90004-8.png?raw=true",
    content : "‘시각장애인 전용도로는  주는 것은 바닥에 배치되어 있는 노란색 점자블록이라는 의미를 담고 있습니다.",
  }
  ,
  {
    id : 2,
    type : "flyers Design",
    title : "메이크짐",
    exper1 : "Photoshop",
    exper2 : "illustration",
    exper3 : "HTML",
    exper4 : "CSS",
    term : "2014.09",
    url : "https://github.com/hyey00n/content/blob/main/repository/90004-9.png?raw=true",
    content : "‘시각장애인 전용도로는  주는 것은 바닥에 배치되어 있는 노란색 점자블록이라는 의미를 담고 있습니다.",
  }
  ,
  {
    id : 2,
    type : "flyers Design",
    title : "에이플러스짐",
    exper1 : "Photoshop",
    exper2 : "illustration",
    exper3 : "HTML",
    exper4 : "CSS",
    term : "2014.09",
    url : "https://github.com/hyey00n/content/blob/main/repository/90004-10.png?raw=true",
    content : "‘시각장애인 전용도로는  주는 것은 바닥에 배치되어 있는 노란색 점자블록이라는 의미를 담고 있습니다.",
  }
  ,
  {
    id : 2,
    type : "flyers Design",
    title : "와이짐 ",
    exper1 : "Photoshop",
    exper2 : "illustration",
    exper3 : "HTML",
    exper4 : "CSS",
    term : "2014.09",
    url : "https://github.com/hyey00n/content/blob/main/repository/90004-11.png?raw=true",
    content : "‘시각장애인 전용도로는  주는 것은 바닥에 배치되어 있는 노란색 점자블록이라는 의미를 담고 있습니다.",
  }
  ,
  {
    id : 2,
    type : "flyers Design",
    title : "광야창호",
    exper1 : "Photoshop",
    exper2 : "illustration",
    exper3 : "HTML",
    exper4 : "CSS",
    term : "2014.09",
    url : "https://github.com/hyey00n/content/blob/main/repository/90004-12.png?raw=true",
    content : "‘시각장애인 전용도로는  주는 것은 바닥에 배치되어 있는 노란색 점자블록이라는 의미를 담고 있습니다.",
  },
  {
    id : 2,
    type : "flyers Design",
    title : "남수대반점 ",
    exper1 : "Photoshop",
    exper2 : "illustration",
    exper3 : "HTML",
    exper4 : "CSS",
    term : "2014.09",
    url : "https://github.com/hyey00n/content/blob/main/repository/90004-13.png?raw=true",
    content : "‘시각장애인 전용도로는  주는 것은 바닥에 배치되어 있는 노란색 점자블록이라는 의미를 담고 있습니다.",
  },
  {
    id : 2,
    type : "flyers Design",
    title : "메디앤컬 필라테스",
    exper1 : "Photoshop",
    exper2 : "illustration",
    exper3 : "HTML",
    exper4 : "CSS",
    term : "2014.09",
    url : "https://github.com/hyey00n/content/blob/main/repository/90004-14.png?raw=true",
    content : "‘시각장애인 전용도로는  주는 것은 바닥에 배치되어 있는 노란색 점자블록이라는 의미를 담고 있습니다.",
  },
  {
    id : 2,
    type : "flyers Design",
    title : "카페63도",
    exper1 : "Photoshop",
    exper2 : "illustration",
    exper3 : "HTML",
    exper4 : "CSS",
    term : "2014.09",
    url : "https://github.com/hyey00n/content/blob/main/repository/90004-15.png?raw=true",
    content : "‘시각장애인 전용도로는  주는 것은 바닥에 배치되어 있는 노란색 점자블록이라는 의미를 담고 있습니다.",
  },
  {
    id : 2,
    type : "flyers Design",
    title : "아트블랑 ",
    exper1 : "Photoshop",
    exper2 : "illustration",
    exper3 : "HTML",
    exper4 : "CSS",
    term : "2014.09",
    url : "https://github.com/hyey00n/content/blob/main/repository/90004-16.png?raw=true",
    content : "‘시각장애인 전용도로는  주는 것은 바닥에 배치되어 있는 노란색 점자블록이라는 의미를 담고 있습니다.",
  }
  


] 
export default data;